import {
    AIProviderJsonRequest,
    AIProviderTextRequest,
    IAIProvider,
    ProviderHealthStatus
} from '../interfaces/IAIProvider';

export class MockAIProvider implements IAIProvider {
    public readonly providerName = 'MockAI';
    public readonly model = 'mock-model';

    public async generateText(request: AIProviderTextRequest): Promise<string> {
        await delay(100);

        if (request.systemPrompt?.includes('software task planner')) {
            return JSON.stringify(createMockTaskPlan());
        }

        return 'Mock provider response.';
    }

    public async generateJSON<T>(request: AIProviderJsonRequest<T>): Promise<T> {
        await delay(100);

        const mockData = createMockTaskPlan();

        if (!request.schema) {
            return mockData as T;
        }

        const parsed = request.schema.safeParse(mockData);
        if (parsed.success) {
            return parsed.data;
        }

        console.error('[MockAI] Invalid mock JSON output.', {
            schemaName: request.schemaName,
            issues: parsed.error.issues
        });

        throw new Error(
            `MockAI returned JSON that does not match the expected schema${request.schemaName ? ` (${request.schemaName})` : ''}.`
        );
    }

    public async testConnection(): Promise<ProviderHealthStatus> {
        return {
            ok: true,
            provider: this.providerName,
            message: 'Mock provider is always available.'
        };
    }
}

function delay(ms: number): Promise<void> {
    return new Promise((resolve) => setTimeout(resolve, ms));
}

function createMockTaskPlan() {
    return [
        {
            title: 'Mock task planning',
            description: 'Generated by the mock provider for local development.',
            priority: 'high',
            dependencies: [],
            expectedOutput: 'A deterministic mock task'
        }
    ];
}
